feat(Workspaces): workspace database exploration
BLSQ/openhexa-frontend pull request #200
Opened 2023-02-08 17:07 UTC by cheikhgwane

Add features for workspace database exploration.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- List tables of a workspace database
- Display details on a database table.

## Screenshots / screencast

![image](https://user-images.githubusercontent.com/25453621/217582633-95dc76c8-e915-4493-b35a-f2d57cedf6e8.png)

![image](https://user-images.githubusercontent.com/25453621/217601367-3758a9fb-96b7-46d1-a5a5-00b6fcea6d97.png)

2023-02-15 08:36 UTC, qgerome requested changes

2023-02-15 08:36 UTC, qgerome commented on src/workspaces/features/DataPreviewDialog/DataPreviewDialog.tsx
> +            {table.columns.map((c: TableColumn, index) => (
(To be updated with the new version of the schema)

2023-02-15 08:36 UTC, qgerome commented on src/workspaces/helpers/database.tsx
> +const trimText = (text: string): string => {
What if there is a correct indent ?
It's better to write the snippet with the correct indent directly than trying to massage it

2023-02-15 08:36 UTC, qgerome commented on src/workspaces/helpers/database.tsx
> +              import pandas as pd
You'll have to remove all indents here to better format the snippet

2023-02-15 11:45 UTC, cheikhgwane commented on src/pages/workspaces/[workspaceSlug]/databases/index.tsx
>            defaultPageSize={5}
Yes, that works for me

2023-02-15 11:48 UTC, cheikhgwane commented on src/pages/workspaces/[workspaceSlug]/databases/index.tsx
> +              <span>{`~ ${value} row${value > 0 ? `'s` : ``} `}</span>
I didn't know we can use i18n that! Thanks for the hint.

2023-02-15 11:51 UTC, cheikhgwane commented on src/workspaces/features/DataPreviewDialog/DataPreviewDialog.tsx
> +            {table.columns.map((c: TableColumn, index) => (
Okay will update it

2023-02-22 10:51 UTC, qgerome requested changes

2023-02-22 10:51 UTC, qgerome commented on src/pages/workspaces/[workspaceSlug]/databases/[tableId].tsx
> +  if (!data?.workspace || !data?.workspace.database) {
Reminder

2023-02-22 10:51 UTC, qgerome commented on src/pages/workspaces/[workspaceSlug]/databases/[tableId].tsx
> +            workspaceId={workspace.slug}
Reminder

2023-02-22 10:51 UTC, qgerome commented on src/pages/workspaces/[workspaceSlug]/databases/[tableId].tsx
> +    if (!data.workspace || !data.workspace.database.table) {
```suggestion
    if (!data.workspace?.database.table) {
```

2023-02-22 10:51 UTC, qgerome commented on src/pages/workspaces/[workspaceSlug]/databases/index.tsx
> +  const onChangePage = ({ page }: { page: number }) => {
Reminder

2023-02-22 10:51 UTC, qgerome commented on src/workspaces/features/DataPreviewDialog/DataPreviewDialog.tsx
> +  if (!data?.workspace) {
```suggestion
  if (!data?.workspace?.database.table) {
```

2023-02-22 10:51 UTC, qgerome commented on src/workspaces/helpers/database.tsx
> +engine = create_engine(os.environ["POSTGRESQL_HEXA_EXPLORE_DEMO_URL"])
I think you could change this by WORKSPACE_DB_URL

2023-02-23 15:06 UTC, qgerome commented
Don't forget to address this problem (seen in the browser's console)
<img width="745" alt="CleanShot 2023-02-23 at 16 05 55@2x" src="https://user-images.githubusercontent.com/1607549/220945867-6f7db48e-5ee6-497b-b5b2-4ab9e688eb0a.png">

2023-02-23 15:20 UTC, cheikhgwane commented
> Don't forget to address this problem (seen in the browser's console) <img alt="CleanShot 2023-02-23 at 16 05 55@2x" width="745" src="https://user-images.githubusercontent.com/1607549/220945867-6f7db48e-5ee6-497b-b5b2-4ab9e688eb0a.png">

Hum I cannot reproduce it, weird !

2023-02-23 15:21 UTC, cheikhgwane commented
> Don't forget to address this problem (seen in the browser's console) <img alt="CleanShot 2023-02-23 at 16 05 55@2x" width="745" src="https://user-images.githubusercontent.com/1607549/220945867-6f7db48e-5ee6-497b-b5b2-4ab9e688eb0a.png">

Okay on it

2023-02-24 09:31 UTC, qgerome approved these changes

2023-02-24 09:31 UTC, merged