fix(Workspaces): hide administration link for non admin/staff user
BLSQ/openhexa-frontend pull request #267
Opened 2023-04-12 12:21 UTC by cheikhgwane

Hide link to  Administration page for non admin/staff user.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- check on user permissions instead of features.

2023-04-12 14:10 UTC, qgerome requested changes

2023-04-12 14:20 UTC, cheikhgwane commented on src/workspaces/features/SidebarMenu/SidebarMenu.tsx
> +            {me.permissions.adminPanel && (
Yes, for sure I'v try it to do it like what we have on openhexa_legacy. So do we intend to create a feature flag adminPanel for the user ?

2023-04-13 14:14 UTC, qgerome approved these changes

2023-04-13 14:14 UTC, qgerome commented on src/workspaces/features/SidebarMenu/SidebarMenu.tsx
> +            {me.permissions.adminPanel && (
Ha no sorry, I mismatch the two.

2023-04-13 14:14 UTC, merged