Feat/hexa 345 usage sections simplification
BLSQ/openhexa-frontend pull request #292
Opened 2023-05-10 11:33 UTC by cheikhgwane

This PR intends to display workspace's database environment variables (name, username, host..) into database page. We've also replaced the usage section for database and connections by links to the corresponding documentation on the wiki.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Display env variables on database view
- Replace usage sections content by links to the wiki

## Screenshots / screencast
Database view
![image](https://github.com/BLSQ/openhexa-frontend/assets/25453621/4d1a133b-2c41-4d1d-95af-2cfed6cec67a)

Connection view
![image](https://github.com/BLSQ/openhexa-frontend/assets/25453621/5a909ec2-65ae-41f1-8bbb-a54f3fac659b)

2023-05-12 07:59 UTC, qgerome requested changes

2023-05-12 07:59 UTC, qgerome commented on src/pages/workspaces/[workspaceSlug]/databases/index.tsx
> +import { DatabaseVariablesSection } from "workspaces/features/DatabaseVariablesSection/DatabaseVariablesSection";
```suggestion
import DatabaseVariablesSection from "workspaces/features/DatabaseVariablesSection";
```

2023-05-12 07:59 UTC, qgerome commented on src/workspaces/features/DatabaseVariablesSection/DatabaseVariablesSection.tsx
> +export const DatabaseVariablesSection = (
No need to export it

2023-05-12 07:59 UTC, qgerome commented on src/workspaces/features/DatabaseVariablesSection/DatabaseVariablesSection.tsx
> +            {field.secret && "*********"}
```suggestion
            {field.secret && field.value && "*********"}
```

2023-05-12 14:42 UTC, qgerome requested changes
In a workspace where I'm a admin, I don't see the '******' for the password. You also need to add a "display" button next to it to display the password if the user has the right.

2023-05-12 14:49 UTC, cheikhgwane commented
> In a workspace where I'm a admin, I don't see the '******' for the password. You also need to add a "display" button next to it to display the password if the user has the right.

It's weird because I 've tested with an admin but it was displayed. It doesn't show  with the non-admin. I'll add the display button.

2023-05-17 12:29 UTC, pvanliefland requested changes
Still to do :

- [x] Adapt the PR after the backend changes
- [x] Replace "variables" by "connection parameters"
- [x] For connections, replace "Usage examples" by usage
- [x] Make the connection view similar to the database view (no separator between fields and usage)

2023-05-19 14:48 UTC, merged