fix(Pipelines): allow scheduling for only pipelines without parameters
BLSQ/openhexa-frontend pull request #381
Opened 2023-07-17 15:04 UTC by cheikhgwane

A short, meaningful PR description. Explain the goal of the PR and the ideas behind it.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- display schedule section only when the pipelines has no parameters.

## How/what to test

## Screenshots / screencast

Pipeline without parameters

![image](https://github.com/BLSQ/openhexa-frontend/assets/25453621/50ca2701-0b87-429d-8139-298ef58c7163)

Pipeline with parameters
![image](https://github.com/BLSQ/openhexa-frontend/assets/25453621/f1d9a935-43fd-4b2c-8e86-c185f915e43e)

2023-07-17 16:00 UTC, qgerome commented
WDYT of adding a permission `schedule` on the pipeline and using this on the frontend ?

2023-07-18 12:30 UTC, qgerome requested changes
IMHO it's too brutal to remove the whole "Scheduling" section when the pipeline cannot be scheduled.

I think it would be better to display the section title and a italic sentence saying something like : "Pipeline with parameters cannot be scheduled"

2023-07-18 12:44 UTC, cheikhgwane commented
Voila  @qgerome !
[Screencast from 07-18-2023 12:41:42 PM.webm](https://github.com/BLSQ/openhexa-frontend/assets/25453621/ef39a162-e735-476e-89be-6ca61774d690)

2023-07-18 12:47 UTC, qgerome approved these changes

2023-07-19 08:53 UTC, merged