feat(Pipelines): Support multiple ints in pipeline
BLSQ/openhexa-frontend pull request #432
Opened 2023-09-18 15:40 UTC by cheikhgwane

Add support for  multiple ints parameter in pipeline.

## Changes

If relevant, please add some screenshots or a short video.

2023-09-19 12:27 UTC, qgerome requested changes

2023-09-19 12:27 UTC, qgerome commented on src/workspaces/features/RunPipelineDialog/ParameterField.tsx
> +      if (parameter.type === "int") {
I think it's better to always take the value of the input instead of trying to deal with the int value and the string value.

2023-09-19 12:27 UTC, qgerome commented
This component is a good candidate for some quick tests

2023-09-30 10:36 UTC, qgerome requested changes

2023-09-30 10:36 UTC, qgerome commented on src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
>          if (parameter.type === "int") {
@cheikhgwane I think we often said it but you do have to handle the case of the float as well.

2023-10-02 08:24 UTC, pvanliefland commented
@cheikhgwane Quentin has reworked part of this PR.

Could you review the changes, and test it throughly in your dev environment?

Thanks!

2023-10-02 08:28 UTC, cheikhgwane commented
> @cheikhgwane Quentin has reworked part of this PR.
> 
> 
> 
> Could you review the changes, and test it throughly in your dev environment?
> 
> 
> 
> Thanks!

Yes, on it.

2023-10-03 11:22 UTC, cheikhgwane commented
@qgerome I've updated the PR to display the parameters values for textarea, and also changed the multiple int param test to use userEvent.paste instead of type (type was returning the value one by one).

2023-10-12 11:45 UTC, merged