fix(PipelineDialog): prevent display of empty value on picker
BLSQ/openhexa-frontend pull request #481
Opened 2023-11-22 12:59 UTC by cheikhgwane

Filter and display the correct connection from pipeline run config.

A short, meaningful PR description. Explain the goal of the PR and the ideas behind it.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Filter and display connection based on the value (if empty return null)
- Change WorkspaceConnectionPicker value type (from Option to string)
- Pass the connection slug to onChange method in ParameterField instead of connection object

## Screenshots / screencast

[Screencast from 11-22-2023 12:53:39 PM.webm](https://github.com/BLSQ/openhexa-frontend/assets/25453621/47053bc8-4288-4502-99c2-f92d7228f0ef)

2023-11-23 10:46 UTC, pvanliefland requested changes
As discussed

2023-11-23 10:46 UTC, pvanliefland commented on src/workspaces/features/WorkspaceConnectionPicker/WorkspaceConnectionPicker.tsx
> +  const defaultValue = useMemo(() => {
Let's call it `comboBoxValue`.

2023-11-23 14:39 UTC, pvanliefland approved these changes
LGTM!

2023-11-23 14:40 UTC, merged

2023-12-04 11:35 UTC, qgerome commented on src/workspaces/features/WorkspaceConnectionPicker/WorkspaceConnectionPicker.tsx
> +      by="name"
Looks weird to me that we use the "name" of the connection as the identifier of the connection.