wip
BLSQ/openhexa-frontend pull request #513
Opened 2023-12-28 07:54 UTC by qgerome

A short, meaningful PR description. Explain the goal of the PR and the ideas behind it.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Change 1
- Change 2

## How/what to test

A few words about what needs to be tested, along with specific testing instructions if needed.

## Screenshots / screencast

If relevant, please add some screenshots or a short video.

2023-12-29 14:45 UTC, pvanliefland approved these changes
Code looks 👍, will test the UX further next year (🥁🙄)

2024-01-03 14:25 UTC, pvanliefland requested changes
Nice, just a `console.log` to remove

2024-01-03 14:25 UTC, pvanliefland commented on src/core/helpers/page.ts
> +        console.log("SECOND");
(leftover)

2024-01-04 08:36 UTC, qgerome commented on src/core/helpers/page.ts
> +        console.log("SECOND");
done

2024-01-08 09:35 UTC, merged