feat(PipelineRun): display run dataset versions
BLSQ/openhexa-frontend pull request #536
Opened 2024-01-17 15:33 UTC by cheikhgwane

When available, display dataset versions created with a PipelineRun

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Add dataset versions table on PipelineRun details page.

2024-01-19 14:15 UTC, qgerome commented
I'd consider that as an output as well so I would add this to the output sections.

2024-01-23 08:22 UTC, qgerome commented
Two tables like this without any explanations on what is what is not idea either. You can add the datasets in the outputs table and add a "type" column that gives an hint to the user on what he is seeing. We do not care to have the "created at" column for the datasets since we are saying that it has been created by this run.

2024-01-24 13:26 UTC, qgerome requested changes

2024-01-24 13:26 UTC, qgerome commented on src/workspaces/features/RunOutputsTable/RunOutputsTable.tsx
> +      <TextColumn name="type" label={t("Type")} accessor="__typename" />
No. This has to be a human string and not the typename of the object.

2024-01-24 13:36 UTC, qgerome commented on src/workspaces/features/RunOutputsTable/RunOutputsTable.tsx
> +      <TextColumn name="type" label={t("Type")} accessor="__typename" />
And add the dataset name in gray and smaller next to the version name

2024-01-24 13:50 UTC, cheikhgwane commented
Updated. See screenshot @qgerome

2024-01-24 14:20 UTC, qgerome requested changes

2024-01-24 14:20 UTC, qgerome commented on src/workspaces/features/RunOutputsTable/RunOutputsTable.tsx
> +    console.log(typename);
console.log

2024-01-24 14:20 UTC, qgerome commented on src/workspaces/features/RunOutputsTable/RunOutputsTable.tsx
> +  const renderOutputType = useCallback((typename: any) => {
you can move this to src/datasets/helpers for example.

2024-01-24 14:20 UTC, qgerome commented on src/workspaces/features/RunOutputsTable/RunOutputsTable.tsx
> +  const renderOutputIcon = useCallback((typename: any) => {
typename is a "str" no ?

2024-01-24 14:20 UTC, qgerome commented on src/workspaces/features/RunOutputsTable/RunOutputsTable.tsx
>    if (!run.outputs.length) {
```suggestion
  if (!data.length) {
```

2024-01-24 15:13 UTC, cheikhgwane commented on src/workspaces/features/RunOutputsTable/RunOutputsTable.tsx
> +  const renderOutputIcon = useCallback((typename: any) => {
Yes, it is.

2024-01-24 16:25 UTC, qgerome commented on src/workspaces/features/RunOutputsTable/RunOutputsTable.tsx
> +                  <span className="text-gray-400 text-sm">{`(${output.dataset.slug})`}</span>
There is two spaces instead of one. No need to put the braces since you already set a grayer color

2024-01-24 16:26 UTC, cheikhgwane commented on src/workspaces/features/RunOutputsTable/RunOutputsTable.tsx
> +                  <span className="text-gray-400 text-sm">{`(${output.dataset.slug})`}</span>
Okay, you'right, should be the name.

2024-01-24 16:39 UTC, qgerome approved these changes

2024-01-26 13:30 UTC, merged