feat(Pipeline): display user associated to the latest version
BLSQ/openhexa-frontend pull request #773
Opened 2024-10-02 11:25 UTC by cheikhgwane

Display user associated to the latest version of a pipeline.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Display assuser, if available
- Change 2

## How/what to test
Upload a new pipeline version :  on a PipelineCard a section with the associated user should be displayed.

## Screenshots / screencast

<img width="721" alt="Screenshot 2024-10-02 at 11 24 57" src="https://github.com/user-attachments/assets/f59285b1-7f1d-4b63-b935-3253c421569b">

2024-10-03 08:17 UTC, qgerome commented
Nice start. I'd increase a bit the margin between the <User /> and the text above. I would remove the "Last version by" that is confusing since it's in another edge of the card. When you work with a card layout, you have to keep the pieces of info together. Here, it just adds a string for nothing. What I propose it to put that <User /> inside a Tooltip that would add the "Last version uploaded on ...." WDYT?

2024-10-03 08:41 UTC, cheikhgwane commented
> Nice start. I'd increase a bit the margin between the and the text above. I would remove the "Last version by" that is confusing since it's in another edge of the card. When you work with a card layout, you have to keep the pieces of info together. Here, it just adds a string for nothing. What I propose it to put that inside a Tooltip that would add the "Last version uploaded on ...." WDYT?

Yes, you're right. It will be better.

2024-10-09 10:01 UTC, qgerome commented
I'd put the User avatar and a tooltip on it that says : "Last version uploaded on {} by {}"

2024-10-15 07:59 UTC, qgerome requested changes

2024-10-15 07:59 UTC, qgerome commented on public/locales/fr/messages.json
> +  "Last version uploaded by {{name}}": "Dernière version téléchargée par {{nom}}",
This is not going to work. The interpolation variable should not change.

2024-10-15 10:08 UTC, qgerome approved these changes

2024-10-15 10:08 UTC, merged