Pipelines notifications
BLSQ/openhexa-frontend pull request #865
Opened 2024-11-12 13:42 UTC by cheikhgwane

We introduce a new, fine-grained way of configuring pipelines notifications : add possibility to specify for each users (recipients) a notification level. We also changed the pipeline page view and introduced a tabular navigation.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Introduce a TabLayout
- Use a tab navigation system (same as dataset page) and split pipeline page into : General, Runs and Scheduling & Notifications section.
- Add a component to handle list/create/edit of a recipient.
- Allow user to override notification for a run (mute)

## Screenshots / screencast

https://github.com/user-attachments/assets/350bf520-097d-40e9-b92b-717a0280fd7a

<img width="1435" alt="Screenshot 2024-11-12 at 16 18 05" src="https://github.com/user-attachments/assets/bcc31a11-91fa-4aeb-9f86-e2d64e42bb79">

2024-11-15 10:27 UTC, qgerome commented
> Also, apply a negative x margin for the recipients table. It's going to look nicer <img alt="Screenshot 2024-11-13 at 16 08 07" width="1074" src="https://private-user-images.githubusercontent.com/1607549/385816067-fb05485d-5b09-4934-b3cb-f48a489f30b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjMwNzUsIm5iZiI6MTczMTY2Mjc3NSwicGF0aCI6Ii8xNjA3NTQ5LzM4NTgxNjA2Ny1mYjA1NDg1ZC01YjA5LTQ5MzQtYjNjYi1mNDhhNDg5ZjMwYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDkyNjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzM5NmJiY2VmMzlmNDRhYTU1MTcxMzY1OWUxNzUzYjJhOGM3MjFkN2JlYzUwN2M4N2RlMmYxMjMwMGY5NmRiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0JcYyIaez3zxSWD_TcumaJF0cy7_CGxp-9OdGlDDMTk">

I didn't see the change in the latest commits. The goal is to have the gray background colour to go from each border left & right of the Block.

2024-11-15 10:29 UTC, qgerome requested changes
There are lot of queries that are executed on the frontend even though it should not since it's already rendered on the backend. By having a quick look at the getServerSideProps of all the pages, I see that it still uses `WorkspaceLayout.prefetch` even though it's not used in the page. You need to implement this function in your layout. Check in the end the queries in the network panel.

2024-11-18 09:07 UTC, cheikhgwane commented
> There are lot of queries that are executed on the frontend even though it should not since it's already rendered on the backend. By having a quick look at the getServerSideProps of all the pages, I see that it still uses `WorkspaceLayout.prefetch` even though it's not used in the page. You need to implement this function in your layout. Check in the end the queries in the network panel.

By trying to debug the issues, I've noticed that in local (for the pipeline  details page) some queries are run twice or the previous page query (e.g : navigate to pipelines/ then go to pipeline/[pipelineCode]) is also run on the page. Still investigating

2024-11-19 12:35 UTC, qgerome requested changes

2024-11-19 12:35 UTC, qgerome commented on src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/notifications.tsx
This page still send a network request for the `WorkspacePipelineNotificationsPage` query (even after updating the branch on the Apollo fix)

2024-11-19 12:35 UTC, qgerome commented on src/workspaces/features/WorkspaceMemberPicker/WorkspaceMemberPicker.tsx
>    const { data, loading } = useQuery<WorkspaceMemberPickerQuery>(
This component triggers two queries on mount. It's better to use a LazyQuery that would fetch the list only when the user open the select.

2024-11-19 12:43 UTC, cheikhgwane commented on src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/notifications.tsx
Yes, I've noticed that, currently on it, thx.

2024-11-26 14:32 UTC, merged