feat: Deprecate custom alerts in favor of toasts from React-Toastify, add toast to file uploads
BLSQ/openhexa-frontend pull request #868
Opened 2024-11-15 13:47 UTC by YolanFery

Introduce React-Toastify and replace custom Alert implementation. Add detailed toasts to the upload file process.

## Changes

- Install `react-toastify`
- Refactor slightly Alert to make it less cumbersome to import in other components (reduce imports by 2)
- Introduce a hook `useUploadFiles` to reduce duplicated logic and add details toasts on user actions

## How/what to test

- Uploading files generate toasts
- Existing Alerts are replace by Toasts except Alert component stay the same, blocking the screen

## Screenshots / screencast
[screen-capture.webm](https://github.com/user-attachments/assets/a404f6c9-ab3b-415e-9ef5-b007cb0b9075)

2024-11-15 13:49 UTC, YolanFery commented on src/core/components/Alert.tsx
> +const Alert = ({ icon, children, onClose }: AlertProps) => {
I am keep `Alert` component because having a blocking dialog replacing the content is a different use case than toasts.

2024-11-15 13:50 UTC, YolanFery commented on src/datasets/features/DeleteDatasetLinkTrigger/DeleteDatasetLinkTrigger.tsx
> -  const router = useRouter();
Was not used

2024-11-18 09:03 UTC, qgerome commented
> Refactor slightly Alert to make it less cumbersome to import in other components (reduce imports by 2)
Do this mean you only need to import one function ?

2024-11-18 09:12 UTC, qgerome commented
![CleanShot 2024-11-18 at 10 11 18@2x](https://github.com/user-attachments/assets/f9b98d08-1b0f-42cd-ac25-76f832a5bf11)
The library takes 6kb gzipped, we can live with this _slight_ increase :)

2024-11-18 10:03 UTC, qgerome commented
> > > Refactor slightly Alert to make it less cumbersome to import in other components (reduce imports by 2)
> > > Do this mean you only need to import one function ?
> 
> Yes sorry if this was not clear. Also it makes it consistent with `toast.error(...)` , `toast.warning(...)`. It's mostly preference so I can revert if we have strong opinion against

no no that's good. I just wanted to make sure I got it right and that you were not talking about something else.

2024-11-19 09:26 UTC, cheikhgwane commented
Nice works Yolan, I've finished testing it. So far I've only one remark : as example for the `toast.error(...)`,  it seems like we can't click on the close button to make it disappear.

https://github.com/user-attachments/assets/bb1730cf-a6b5-4a80-a2d3-f5ece216227e

2024-11-19 10:16 UTC, qgerome requested changes
Like it. It improves the UX. I do feel that we need to display the errors longer or only remove them when clicked by the user though. When I uploaded an already existing file in the bucket, I barely had the time to look at which file was already there that it disappeared.

2024-11-19 10:16 UTC, qgerome commented on src/datasets/features/DeleteDatasetTrigger/DeleteDatasetTrigger.tsx
> +  useRouter();
Not sure why it's left as it is. Can't you just remove this call ?

2024-11-19 10:16 UTC, qgerome commented on src/pages/pipelines/[pipelineId]/run.tsx
> +      toast.error((err as Error).message ?? "An unexpected error occurred.");
```suggestion
      toast.error((err as Error).message ?? t("An unexpected error occurred."));
```

2024-11-19 12:28 UTC, YolanFery commented on src/core/hooks/useUploadFiles.ts
Moved, thanks

2024-11-19 12:29 UTC, YolanFery commented on src/pages/pipelines/[pipelineId]/run.tsx
> +      toast.error((err as Error).message ?? "An unexpected error occurred.");
Good catch :)

2024-11-19 12:29 UTC, YolanFery commented
> Like it. It improves the UX. I do feel that we need to display the errors longer or only remove them when clicked by the user though. When I uploaded an already existing file in the bucket, I barely had the time to look at which file was already there that it disappeared.

Thanks, I increased the timeout from 2s to 5s

2024-11-19 13:00 UTC, cheikhgwane commented
> > Nice works Yolan, I've finished testing it. So far I've only one remark : as example for the `toast.error(...)`, it seems like we can't click on the close button to make it disappear.
> > Screen.Recording.2024-11-19.at.09.22.20.mov
> 
> Thanks for the review. I tested on Chrome, Firefox and Safari. The cross seems to be working for me. On which browser do you have issue ? Can you try on another one ?
> 
> Thanks to this verification, I have found and fixed a bug in Safari 🥳

Was testing on chrome, but it's okay now. Ths

2024-11-20 09:42 UTC, qgerome approved these changes

2024-11-20 09:42 UTC, merged