fix(Datasets): prevent overflow, add pagination
BLSQ/openhexa-frontend pull request #920
Opened 2024-12-06 08:39 UTC by cheikhgwane

Implements Mariano's feedbacks on dataset explorer.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Force flex-items to only take parent div
- Overflow component on the Columns metadata viewer

## How/what to test

Upload a dataset version file (tabular data) with long columns names and/or many columns to see if the table is displayed correctly and scroll if needed. 

## Screenshots / screencast

https://github.com/user-attachments/assets/c2b07617-43b5-4206-bfa7-0366125f8ee2

2024-12-06 14:53 UTC, qgerome requested changes
If you set an overflow, it's going to cut the shadows and border of the column blocks. This is something I already fixed in your last PR. Please be more careful.

2024-12-06 14:57 UTC, cheikhgwane commented
> If you set an overflow, it's going to cut the shadows and border of the column blocks. This is something I already fixed in your last PR. Please be more careful.

Yes, I saw that. The issue was the scrolling was not working for that section that's why I tried this. I'll look for another way.

2024-12-09 11:35 UTC, cheikhgwane commented
The failed build is due to React 19 being used on the CI and some dependencies are not compatible yet (although the current branch use React 18, to investigate)

2024-12-09 12:46 UTC, qgerome approved these changes

2024-12-09 14:09 UTC, merged